name: ilebora_stk
description: BoraSTK is a Flutter package for simplified integration of Safaricom's Lipa Na M-Pesa Online API, enabling seamless STK push payments in mobile applications.
license: MIT
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_client_sse: ^2.0.1
  formz: ^0.6.1
  http: ^1.1.0
  ilebora_push: ^0.0.2
  package_info: ^2.0.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/mpesa.png
    - assets/images/icon.png